spring:
  application:
    name: MailForge-ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes[0].uri: lb://UserService


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
